from __future__ import annotations
import os
import json

CURRENT_DIR = os.path.dirname(os.path.abspath(__file__))
CUPERTINO_MAP_PATH = os.path.join(CURRENT_DIR, "icons", "cupertino_icons_map.json")
try:
    with open(CUPERTINO_MAP_PATH, "r") as f:
        CUPERTINO_ICONS_MAP = json.load(f)
except Exception:
    CUPERTINO_ICONS_MAP = {}

TINY_DFR_BUILTIN_ICONS = {
    'backlight_high', 'backlight_low', 'brightness_high', 'brightness_low',
    'fast_forward', 'fast_rewind', 'mic_off', 'play_pause',
    'search', 'volume_down', 'volume_off', 'volume_up'
}


STANDARD_MEDIA_LAYOUT = [
    {
        "type": "Icon",
        "val": "brightness_low",
        "action": "BrightnessDown",
        "stretch": 1,
        "custom_icon_path": None,
        "spacer_type": "flexible",
    },
    {
        "type": "Icon",
        "val": "brightness_high",
        "action": "BrightnessUp",
        "stretch": 1,
        "custom_icon_path": None,
        "spacer_type": "flexible",
    },
    {
        "type": "Icon",
        "val": "mic_off",
        "action": "MicMute",
        "stretch": 1,
        "custom_icon_path": None,
        "spacer_type": "flexible",
    },
    {
        "type": "Icon",
        "val": "search",
        "action": "Search",
        "stretch": 1,
        "custom_icon_path": None,
        "spacer_type": "flexible",
    },
    {
        "type": "Icon",
        "val": "backlight_low",
        "action": "IllumDown",
        "stretch": 1,
        "custom_icon_path": None,
        "spacer_type": "flexible",
    },
    {
        "type": "Icon",
        "val": "backlight_high",
        "action": "IllumUp",
        "stretch": 1,
        "custom_icon_path": None,
        "spacer_type": "flexible",
    },
    {
        "type": "Icon",
        "val": "fast_rewind",
        "action": "PreviousSong",
        "stretch": 1,
        "custom_icon_path": None,
        "spacer_type": "flexible",
    },
    {
        "type": "Icon",
        "val": "play_pause",
        "action": "PlayPause",
        "stretch": 1,
        "custom_icon_path": None,
        "spacer_type": "flexible",
    },
    {
        "type": "Icon",
        "val": "fast_forward",
        "action": "NextSong",
        "stretch": 1,
        "custom_icon_path": None,
        "spacer_type": "flexible",
    },
    {
        "type": "Icon",
        "val": "volume_off",
        "action": "Mute",
        "stretch": 1,
        "custom_icon_path": None,
        "spacer_type": "flexible",
    },
    {
        "type": "Icon",
        "val": "volume_down",
        "action": "VolumeDown",
        "stretch": 1,
        "custom_icon_path": None,
        "spacer_type": "flexible",
    },
    {
        "type": "Icon",
        "val": "volume_up",
        "action": "VolumeUp",
        "stretch": 1,
        "custom_icon_path": None,
        "spacer_type": "flexible",
    },
]


def standard_media_layout():
    return [dict(item) for item in STANDARD_MEDIA_LAYOUT]


def _format_action(action):
    if not action:
        return None

    # Convert comma-separated string to a list of clean keys
    if isinstance(action, str):
        action = action.replace("+", ",")
        if "," not in action and " " in action:
            action = action.replace(" ", ",")
            
        if "," in action:
            action = [item.strip() for item in action.split(",") if item.strip()]
        else:
            action = action.strip()

    # Format list/tuple actions
    if isinstance(action, (list, tuple)):
        action_list = [item.strip() for item in action if item and item.strip() and item.strip() != "None"]
        if not action_list:
            return None
        if len(action_list) == 1:
            return f'"{action_list[0]}"'
        return "[" + ", ".join(f'"{item}"' for item in action_list) + "]"

    # Format single string actions
    if isinstance(action, str):
        if action and action != "None":
            return f'"{action}"'

    return None


def _format_spacer(stretch, spacer_type):
    if spacer_type == "small":
        return "Stretch = 1"
    if spacer_type == "large":
        return "Stretch = 2"
    return f"Stretch = {stretch if stretch and stretch > 1 else 5}"


def build_config_toml(
    media_specs, 
    primary_specs, 
    *, 
    media_layer_default, 
    show_button_outlines, 
    enable_pixel_shift, 
    adaptive_brightness, 
    font_template
):
    lines = [
        "# Generated by Touch Bar Enhancer",
        f"MediaLayerDefault = {'true' if media_layer_default else 'false'}",
        f"ShowButtonOutlines = {'true' if show_button_outlines else 'false'}",
        f"EnablePixelShift = {'true' if enable_pixel_shift else 'false'}",
        f"AdaptiveBrightness = {'true' if adaptive_brightness else 'false'}",
        f'FontTemplate = "{font_template}"',
        "",
    ]
    
    def _build_layer(specs, layer_name):
        layer_lines = [f"{layer_name} = ["]
        for item in specs:
            item_type = item.get("type", "Text")
            val = item.get("val", "")
            action = item.get("action", "")
            stretch = item.get("stretch", 1)

            if item_type == "Spacer":
                layer_lines.append(f"    {{ {_format_spacer(stretch, item.get('spacer_type', 'flexible'))} }},")
                continue

            if item_type == "Text":
                layer_lines.append(f'    {{ Text = "{val}"')
            elif item_type == "Icon":
                if val in CUPERTINO_ICONS_MAP and val not in TINY_DFR_BUILTIN_ICONS:
                    icon_val = f"cupertino_{val}"
                elif val.startswith("cupertino_") and val[10:] in CUPERTINO_ICONS_MAP and val[10:] not in TINY_DFR_BUILTIN_ICONS:
                    icon_val = val
                else:
                    icon_val = val
                layer_lines.append(f'    {{ Icon = "{icon_val}"')
            elif item_type == "Time":
                layer_lines.append(f'    {{ Time = "{val}"')
            elif item_type == "Battery":
                layer_lines.append(f'    {{ Battery = "{val}"')
            else:
                layer_lines.append(f'    {{ Text = "{val}"')

            action_fmt = _format_action(action)
            if action_fmt is not None:
                layer_lines[-1] += f", Action = {action_fmt}"
                if item_type == "Time":
                    layer_lines[-1] += f", Stretch = {stretch}" if stretch > 1 else ""
                elif item_type == "Battery":
                    layer_lines[-1] += f", Stretch = {stretch}" if stretch > 1 else ""
                elif stretch > 1:
                    layer_lines[-1] += f", Stretch = {stretch}"
            elif stretch > 1 and item_type != "Spacer":
                layer_lines[-1] += f", Stretch = {stretch}"

            layer_lines[-1] += " },"
        layer_lines.append("]")
        return layer_lines

    if media_specs:
        lines.extend(_build_layer(media_specs, "MediaLayerKeys"))
        lines.append("")
        
    if primary_specs:
        lines.extend(_build_layer(primary_specs, "PrimaryLayerKeys"))
        lines.append("")
    
    return "\n".join(lines) + "\n"
